### ISSUE TITLE
Why divide the UNet output by 320?

### ISSUE THREAD

**Issue by qizhuli** [dulucas/Displacement_Field#2]
In both the RGB guided version and the depth only version, you divide the UNet output by 320, could you please explain how you came up with this number, and why this step?

https://github.com/dulucas/Displacement_Field/blob/746ba335290a1558b0fad9df344d7d9af6b6c3d4/model/nyu/df_nyu_rgb_guidance/df.py#L20

https://github.com/dulucas/Displacement_Field/blob/746ba335290a1558b0fad9df344d7d9af6b6c3d4/model/nyu/df_nyu_depth_only/df.py#L20

Many thanks!

**Comment by dulucas** [comment]
Hi, 320 here is a empirical hyperparameter. I have also tried with 240/480, they work just fine. This hyperparameter is applied to limit the amplitude of predicted displacement field at the beginning of the training. If this hyperparameter is not used, the network struggles to converge to satisfactory results. Hope it helps.

**Comment by qizhuli** [comment]
Thank you for the swift explanation. 

Here's another question somewhat related. Immediately after the division step, you clamped the `displacement_map` to the range of plus-minus `max_disp`, which is set to 0.9. Could you please clarify what this means semantically/physically? Many thanks.

**Comment by dulucas** [comment]
Hi, this is to limite the range of predicted displacement field, to avoid the predicted displacement exceeding the image boundaries. I tried training the model without this line of code, the model works just fine.
