### ISSUE TITLE
download.sh does not work

### ISSUE THREAD

**Issue by Jacob-Yao** [dulucas/Displacement_Field#4]
Thanks for your work.
I faced some problem when executing "download.sh". Terminal reports:
 "Connecting to horatio.cs.nyu.edu (horatio.cs.nyu.edu)|216.165.22.17|:80... failed: Connection refused".

**Comment by dulucas** [comment]
Hi, the dataset can be downloaded from : https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html
You can not download the data because their sever has crashed.
Please contact the [Nathan Silberman](https://cs.nyu.edu/~silberman/index.html), who is in charge of this dataset.
Thanks

**Comment by Jacob-Yao** [comment]
Oh thanks, I just realize that it's the dataset itself. I thought it is some labels by your team.
Thanks!
