### ISSUE TITLE
when I run the train.py, my PC is stucking

### ISSUE THREAD

**Issue by ShihuaiXu** [dulucas/Displacement_Field#5]
I do not know the reason

**Comment by dulucas** [comment]
It works fine for me. Due to your limited infomation, I'm afraid that I can not help you much. I recommand you to check your environment and device. Hope it helps.

**Comment by ShihuaiXu** [comment]
thanks for your quickly reply, I locate the method which stucks my PC, 
it is this code, train_loader, train_sampler = get_train_loader(engine, NYUDataset) in the model/nyu/df_nyu_depth_only/dataloader.py
I download the nyu_depth_v2_labeled.mat and put it into the ./dataset, the log is always
28 16:56:30 PyTorch Version 0.4.1, Furnace Version 0.1.1
28 16:56:30 using devices 0
and there is no GPU memory use, should I wait it for 5 min or longer?

**Comment by ShihuaiXu** [comment]
thanks for your quickly reply, I locate the method which stucks my PC, 
it is this code, train_loader, train_sampler = get_train_loader(engine, NYUDataset) in the model/nyu/df_nyu_depth_only/dataloader.py
I download the nyu_depth_v2_labeled.mat and put it into the ./dataset, the log is always
28 16:56:30 PyTorch Version 0.4.1, Furnace Version 0.1.1
28 16:56:30 using devices 0
and there is no GPU memory use, should I wait it for 5 min or longer?

**Comment by dulucas** [comment]
Hi, I think the problem may come from your device. How many cpu you have on your device? I recommend you to reduce the number of threads used for training (the variable "num_worker" in config.py).

**Comment by ShihuaiXu** [comment]
My device only has one cpu which is i5-4590. I will try it, thank you very much

**Comment by dulucas** [comment]
Training on a single cpu may be difficult and definitely slow, it would be better to use a GPU for training and cpus to feed data.

**Comment by ShihuaiXu** [comment]
Yes, I change the num_worker from 4 to 0, it still slow and shows the MemoryError. I want to use the GPU to fedd the data, could please tell me how to set it? I use the default seeting, it uses the cpu to feed the data

**Comment by dulucas** [comment]
The num_worker should be at least 1 to feed data. To feed the data with GPU, you should firstly read the read with cpu and then transfer the read data from cpu to GPU. The default setting will automaticlly use GPU for traininig, but it will switch to cpu if no GPU device detected.

**Comment by ShihuaiXu** [comment]
作者您好, 我卡在加载数据这一步了, 还没到GPU训练代码这一步, 现在报了memoryError这个错误, 是否是因为.mat文件太大的原因导致的, 将近3个G了, log如下
28 17:30:36 PyTorch Version 0.4.1, Furnace Version 0.1.1
28 17:30:36 using devices 0
28 17:31:07 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "/home/xsh/Displacement_Field/model/nyu/df_nyu_depth_only/train.py", line 45, in <module>
    train_loader, train_sampler = get_train_loader(engine, NYUDataset)
  File "/home/xsh/Displacement_Field/model/nyu/df_nyu_depth_only/dataloader.py", line 57, in get_train_loader
    config.niters_per_epoch * config.batch_size)
  File "/home/xsh/Displacement_Field/lib/datasets/nyu.py", line 22, in __init__
    self._imgs_source, self._labels_source = self._load_data_file(setting['data_source'])
  File "/home/xsh/Displacement_Field/lib/datasets/nyu.py", line 82, in _load_data_file
    images = np.array(data_file['images'], dtype=np.float64).transpose(0, 3, 2, 1)
MemoryError

**Comment by dulucas** [comment]
对，你这个是mat文件太大导致的

**Comment by ShihuaiXu** [comment]
那请问咋解决嘞, 下载过来的源文件就这么大

**Comment by dulucas** [comment]
买个新机器，只有这个办法了

**Comment by ShihuaiXu** [comment]
明白了, 请问您是在服务器上跑的吗

**Comment by dulucas** [comment]
对的

**Comment by ShihuaiXu** [comment]
好的 多谢啦
