### ISSUE TITLE
supervised or unsupervised?

### ISSUE THREAD

**Issue by jilner** [dulucas/Displacement_Field#7]
Is this method supervised？  Do we need real ground truth of depth as the surveillance information?

**Comment by dulucas** [comment]
This method is supervised. In this repo, we use real depth as training data and blurring the depth image as our input. But, we also tried with synthetic depth and find the model trained with synthetic depth works just fine on real images. More interestingly, the model can be trained on synthetic images that are completely different from the depth images while still can maintain a certain level of performance. Hope it helps.

**Comment by jilner** [comment]
thx





---Original---
