### ISSUE TITLE
Model Problem

### ISSUE THREAD

**Issue by JuewenPeng** [dulucas/Displacement_Field#8]
Hi, in your paper, is the refinement model trained on different depth estimation methods separately, or done in the same way with this repo?

**Comment by dulucas** [comment]
Hi, the model used for depth refinement in our paper is trained by attaching on the head of a monocular depth estimation model(SharpNet specifically) for all different depth estimation methods, which produces results with higher numerical results. Models trained with this repo are a bit lower numerically, but visually much better, and simpler. Hope it helps.

**Comment by JuewenPeng** [comment]
Thanks for your reply.
