### ISSUE TITLE
Download too slow  for nyu_depth_v2_labeled.mat

### ISSUE THREAD

**Issue by gwc2017180303** [dulucas/Displacement_Field#9]
Do you have other ways to download this dataset?Thank you.

**Comment by JuewenPeng** [comment]
链接：https://pan.baidu.com/s/1I5er7p5CHqRseyZRem6gEA 
提取码：mgs1 
复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by gwc2017180303** [comment]
> 链接：https://pan.baidu.com/s/1I5er7p5CHqRseyZRem6gEA
> 提取码：mgs1
> 复制这段内容后打开百度网盘手机App，操作更方便哦

thank you very much！
